### ISSUE TITLE
갑자기 txt 관련 명령어가 삭제된 듯합니다.

### ISSUE THREAD

**Issue by jeongjo13** [1ongames/vandal-bot#7]
제 깃에서 복붙하시다가 txt 관련 명령어를 삭제하신 듯합니다.

그리고 제 깃만 너무 가져다 쓰지 마시고 직접 개발을 해보시는 걸 추천합니다.

**Comment by jeongjo13** [comment]
https://github.com/1ongames/vandal-bot/commit/8b811e9ecc934321440d634a4009689c6755691d

**Comment by 1ongames** [comment]
![Screenshot_20240606_135240_Chrome](https://github.com/1ongames/vandal-bot/assets/114791859/7916dd94-272c-4ea4-93d1-b2aa8a76edad)
![Screenshot_20240606_135234_Chrome](https://github.com/1ongames/vandal-bot/assets/114791859/11693b9c-1d0f-4d01-8856-7f033f50e425)

txt를 통한 명령어는 현재 유지되어있으며, 최근 업데이트는 제가 코드 만지다가 꼬여서 다시 포크해오고, 기존 명령어(txt 응용) 등을 일부 수정했습니다.

**Comment by 1ongames** [comment]
다시 확인해보니 함수가 빠져버렸군요. 일단 다시 함수 추가해뒀습니다.
